name: smart_warehouse

packages:
  - '*'
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  pub_upgrade:
    exec: flutter pub upgrade
  get:
    exec: flutter pub get
  generate:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  test:
    exec: flutter test --no-pub
    packageFilters:
      dirExists:
        - test
  test:coverage:
    run: |
      dart run tool/gen_coverage_imports.dart
      melos exec --dir-exists=test -- flutter test --coverage --no-pub
      dart run tool/check_coverage.dart
